services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
  cache:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data
  backend:
    build: ./
    ports: 
      - '1337'
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    depends_on:
      - mongodb
      - cache
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend 
    ports:
      - "80:80"
volumes:
  data:
  cache:
