services:
  backend:
    build: ./
    ports: 
      - '1337:1337'
    volumes:
      - type: bind
        source: ./src
        target: /app/src
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
volumes:
  data:
